#!/bin/bash

mkdir original_files
cp *.tsv original_files/

LIST=`ls -1 *.tsv`

for barcode in $LIST
do
    awk 'BEGIN {FS=OFS="\t"} NR>1 {genus[$3]+=$1} END {for (x in genus) {printf "%s\t%.20f\n", x, genus[x]}}' original_files/$barcode | sort -n > ./$barcode
    awk '{print $0 "\t" (NR<1?"name_file":FILENAME)}' $barcode > tempfile.$barcode.temp
done

cat *.temp | awk '{print substr($0, 1, length($0)-4)}' | awk -F $'\t' ' { t = $2; $2 = $3; $3 = t; print; } ' OFS=$'\t' | \
awk 'BEGIN { OFS="\t"; print "Elements", "Barcodes", "Abundance"} { print $0, "" } ' | \
awk -F"\t" '
NR>1{
    map[$1,$2] = sprintf("%.20f", $3)
    name[$1]++
    value[$2]++
}
END{
    printf "Elements"
    n = asorti(value, v_s)
    for(i=1; i<=n; i++) {
        printf "%s%s", FS, v_s[i]
    }
    print ""
    m = asorti(name, n_s)
    for(i=1; i<=m; i++) {
        printf "%s", n_s[i]
        for(j=1; j<=n; j++) {
            printf "%s%s", FS, map[n_s[i],v_s[j]]
        }
        print ""
    }
}' | awk 'BEGIN { FS = OFS = "\t" } { for(i=1; i<=NF; i++) if($i ~ /^ *$/) $i = 0 }; 1' > table_summary.txt

rm tempfile*
echo Result saved as table_summary.txt.
